//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EhkBackend.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admins
    {
        public string admin_id { get; set; }
        public string admin_name { get; set; }
        public string admin_pwd { get; set; }
        public string admin_realName { get; set; }
        public string admin_phone { get; set; }
        public string admin_back1 { get; set; }
        public string admin_back2 { get; set; }
        public string admin_back3 { get; set; }
    }
}
