//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EhkBackend.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public string Account { get; set; }
        public string SUBSCRIBER { get; set; }
        public string CORRADDR1 { get; set; }
        public string BILLNO { get; set; }
        public Nullable<System.DateTime> BILLDATE { get; set; }
        public Nullable<decimal> PREVREAD { get; set; }
        public Nullable<decimal> READs { get; set; }
        public Nullable<decimal> CHARGE { get; set; }
        public Nullable<decimal> BFAMT { get; set; }
        public Nullable<decimal> ADDAMT { get; set; }
        public Nullable<decimal> ODDCENT { get; set; }
        public string READTYPE { get; set; }
        public Nullable<decimal> BILLAMT { get; set; }
        public Nullable<decimal> PAYAMT { get; set; }
    }
}
