//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EhkBackend.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EFeesEntities : DbContext
    {
        public EFeesEntities()
            : base("name=EFeesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<acemail> acemail { get; set; }
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Bill> Bill { get; set; }
        public virtual DbSet<M_BILLS> M_BILLS { get; set; }
        public virtual DbSet<m_bills1> m_bills1 { get; set; }
        public virtual DbSet<m_bills2> m_bills2 { get; set; }
        public virtual DbSet<m_bills3> m_bills3 { get; set; }
        public virtual DbSet<M_Detail> M_Detail { get; set; }
        public virtual DbSet<m_detail1> m_detail1 { get; set; }
        public virtual DbSet<m_detail2> m_detail2 { get; set; }
        public virtual DbSet<m_detail3> m_detail3 { get; set; }
        public virtual DbSet<month1> month1 { get; set; }
        public virtual DbSet<month2> month2 { get; set; }
        public virtual DbSet<month3> month3 { get; set; }
        public virtual DbSet<MR> MR { get; set; }
        public virtual DbSet<UserAccount> UserAccount { get; set; }
        public virtual DbSet<UserAddress> UserAddress { get; set; }
        public virtual DbSet<USERID> USERID { get; set; }
        public virtual DbSet<ReportMeterReading> ReportMeterReading { get; set; }
    }
}
