//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EhkBackend.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_bills2
    {
        public string account { get; set; }
        public string billno { get; set; }
        public Nullable<decimal> prev { get; set; }
        public Nullable<decimal> pres { get; set; }
        public Nullable<decimal> unit { get; set; }
        public string type { get; set; }
        public Nullable<decimal> bf { get; set; }
        public Nullable<decimal> odd { get; set; }
        public Nullable<decimal> chg { get; set; }
        public Nullable<decimal> misc { get; set; }
        public Nullable<decimal> bill { get; set; }
        public Nullable<decimal> auto { get; set; }
        public string descs { get; set; }
        public string name { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public string date { get; set; }
    }
}
