//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EhkBackend.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_BILLS
    {
        public string ACCOUNT { get; set; }
        public string BILLNO { get; set; }
        public Nullable<decimal> PREV { get; set; }
        public Nullable<decimal> PRES { get; set; }
        public Nullable<decimal> UNIT { get; set; }
        public Nullable<decimal> RATE { get; set; }
        public string TYPE { get; set; }
        public Nullable<decimal> BF { get; set; }
        public Nullable<decimal> ODD { get; set; }
        public Nullable<decimal> CHG { get; set; }
        public Nullable<decimal> MISC { get; set; }
        public Nullable<decimal> BILL { get; set; }
        public Nullable<decimal> AUTO { get; set; }
        public string DESC1 { get; set; }
        public string NAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<System.DateTime> DUDATE { get; set; }
        public string EMAIL { get; set; }
    }
}
