//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EhkBackend.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Detail
    {
        public string ACCOUNT { get; set; }
        public string BILLNO { get; set; }
        public string ACTCODE1 { get; set; }
        public Nullable<decimal> CHARGEAMT1 { get; set; }
        public string ACTCODE2 { get; set; }
        public Nullable<decimal> CHARGEAMT2 { get; set; }
        public string ACTCODE3 { get; set; }
        public Nullable<decimal> CHARGEAMT3 { get; set; }
        public string ACTCODE4 { get; set; }
        public Nullable<decimal> CHARGEAMT4 { get; set; }
        public string ACTCODE5 { get; set; }
        public Nullable<decimal> CHARGEAMT5 { get; set; }
        public string ACTCODE6 { get; set; }
        public Nullable<decimal> CHARGEAMT6 { get; set; }
        public string ACTCODE7 { get; set; }
        public Nullable<decimal> CHARGEAMT7 { get; set; }
        public string ACTCODE8 { get; set; }
        public Nullable<decimal> CHARGEAMT8 { get; set; }
        public string ACTCODE9 { get; set; }
        public Nullable<decimal> CHARGEAMT9 { get; set; }
    }
}
