//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EhkBackend.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_detail1
    {
        public string account { get; set; }
        public string billno { get; set; }
        public string actcode1 { get; set; }
        public Nullable<decimal> chargeamt1 { get; set; }
        public string actcode2 { get; set; }
        public Nullable<decimal> chargeamt2 { get; set; }
        public string actcode3 { get; set; }
        public Nullable<decimal> chargeamt3 { get; set; }
        public string actcode4 { get; set; }
        public Nullable<decimal> chargeamt4 { get; set; }
        public string actcode5 { get; set; }
        public Nullable<decimal> chargeamt5 { get; set; }
        public string actcode6 { get; set; }
        public Nullable<decimal> chargeamt6 { get; set; }
        public string actcode7 { get; set; }
        public Nullable<decimal> chargeamt7 { get; set; }
        public string actcode8 { get; set; }
        public Nullable<decimal> chargeamt8 { get; set; }
        public string actcode9 { get; set; }
        public Nullable<decimal> chargeamt9 { get; set; }
    }
}
