//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EhkBackend.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public string users_id { get; set; }
        public string users_name { get; set; }
        public string users_bu1 { get; set; }
        public Nullable<int> users_bu2 { get; set; }
        public Nullable<bool> users_bu3 { get; set; }
        public Nullable<bool> delflag { get; set; }
        public string users_pwd { get; set; }
        public string users_email { get; set; }
        public Nullable<int> address_id { get; set; }
    }
}
